"""RLS isolation test for engine_dispatch_tokens.

Asserts that an EngineDispatchToken inserted under tenant A is NOT
visible from tenant B's RLS context.

Design notes
------------
The test suite bootstraps the test database via ``Base.metadata.create_all``
(see conftest._create_tables). That creates tables but does NOT run Alembic
migrations, so RLS is disabled and no policies exist by default.

To test the actual policy text from migration 0024, this module applies the
policies onto the test DB inside a session-scoped fixture (Option A from the
Phase 3C.2 plan). Key mechanics:

1. ``_apply_engine_token_rls`` (session fixture):
   - Enables RLS on ``engine_dispatch_tokens``.
   - Creates the canonical ``tenant_isolation`` + ``service_bypass`` policies
     (identical SQL to migration 0024).
   - Grants ``nexus_app`` SELECT, INSERT, UPDATE on the table so that the
     test can switch to the ``nexus_app`` role (``NOBYPASSRLS``) and have
     the policy actually enforced. Without this grant, the role switch would
     cause a permission-denied error rather than testing policy logic.
   - Tears everything down (drop policies + disable RLS + revoke) at session
     end so no state leaks to subsequent runs.

2. The isolation test uses raw asyncpg connections (not the rollback-wrapped
   ``db`` fixture) so that committed data survives across connection
   boundaries. ``SET LOCAL`` reverts at transaction end, which is fine because
   each step opens its own connection.

3. Crucially, the SELECT under tenant B's context issues
   ``SET LOCAL ROLE nexus_app`` before setting ``app.current_tenant``.
   ``nexus_app`` has ``rolbypassrls = false`` (confirmed in pg_roles), so the
   ``tenant_isolation`` policy is actually evaluated. Without the role switch,
   the test connection runs as ``postgres`` (``rolbypassrls = true``) and the
   policy is silently skipped.

4. Note: ``SET LOCAL`` for GUC values (``app.current_tenant``) cannot use
   bound parameters in asyncpg — PostgreSQL doesn't allow ``$1`` in GUC
   assignment statements. UUIDs are inlined directly; they're safe to
   interpolate because they're generated by ``uuid.uuid4()`` and validated
   as UUIDs at creation time.

Negative-control verification
------------------------------
After the positive test passes, ``_CREATE_PERMISSIVE_POLICY`` replaces the
canonical policy with ``USING (true) WITH CHECK (true)``. The test is then
expected to FAIL — ``assert rows == []`` raises because tenant B can now see
tenant A's row. Restoring the correct policy makes the test pass again.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta

import pytest
import pytest_asyncio
import sqlalchemy
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine

from tests.conftest import (
    TEST_DATABASE_URL,
    create_test_client,
    create_test_user,
)
from tests.test_migration_0014 import _make_assignment_with_stage

pytestmark = pytest.mark.asyncio

# ---------------------------------------------------------------------------
# A separate engine for this module — used for DDL and for per-test data
# connections that need committed transactions (not the rollback savepoint
# that the ``db`` fixture uses).
# ---------------------------------------------------------------------------
_rls_engine = create_async_engine(TEST_DATABASE_URL, echo=False)

# ---------------------------------------------------------------------------
# RLS policy SQL — mirrors migration 0024 exactly.
# ---------------------------------------------------------------------------
_ENABLE_RLS = "ALTER TABLE engine_dispatch_tokens ENABLE ROW LEVEL SECURITY"
_DISABLE_RLS = "ALTER TABLE engine_dispatch_tokens DISABLE ROW LEVEL SECURITY"
_GRANT_NEXUS_APP = (
    "GRANT SELECT, INSERT, UPDATE ON engine_dispatch_tokens TO nexus_app"
)
_REVOKE_NEXUS_APP = (
    "REVOKE SELECT, INSERT, UPDATE ON engine_dispatch_tokens FROM nexus_app"
)
_DROP_TENANT_POLICY = (
    'DROP POLICY IF EXISTS "tenant_isolation" ON engine_dispatch_tokens'
)
_DROP_SERVICE_POLICY = (
    'DROP POLICY IF EXISTS "service_bypass" ON engine_dispatch_tokens'
)
_CREATE_TENANT_POLICY = """
    CREATE POLICY "tenant_isolation" ON engine_dispatch_tokens
      USING      (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
      WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
"""
_CREATE_SERVICE_POLICY = """
    CREATE POLICY "service_bypass" ON engine_dispatch_tokens
      USING (current_setting('app.bypass_rls', true) = 'true')
"""

# Permissive replacement used during negative-control verification.
# Replace tenant_isolation with this, re-run the test, and it MUST fail.
_CREATE_PERMISSIVE_POLICY = """
    CREATE POLICY "tenant_isolation" ON engine_dispatch_tokens
      USING      (true)
      WITH CHECK (true)
"""


@pytest_asyncio.fixture(scope="session", loop_scope="session")
async def _apply_engine_token_rls(_create_tables: None):  # noqa: PT004
    """Enable RLS + install policies + grant nexus_app for the test session.

    After yield (session teardown): drop policies, disable RLS, revoke grant.
    """
    async with _rls_engine.begin() as conn:
        await conn.execute(sqlalchemy.text(_ENABLE_RLS))
        await conn.execute(sqlalchemy.text(_DROP_TENANT_POLICY))
        await conn.execute(sqlalchemy.text(_DROP_SERVICE_POLICY))
        await conn.execute(sqlalchemy.text(_CREATE_TENANT_POLICY))
        await conn.execute(sqlalchemy.text(_CREATE_SERVICE_POLICY))
        await conn.execute(sqlalchemy.text(_GRANT_NEXUS_APP))

    yield

    async with _rls_engine.begin() as conn:
        await conn.execute(sqlalchemy.text(_DROP_TENANT_POLICY))
        await conn.execute(sqlalchemy.text(_DROP_SERVICE_POLICY))
        await conn.execute(sqlalchemy.text(_DISABLE_RLS))
        await conn.execute(sqlalchemy.text(_REVOKE_NEXUS_APP))


# ---------------------------------------------------------------------------
# Helper: seed the minimal FK graph and return a Session.id under `tenant`.
# ---------------------------------------------------------------------------
async def _seed_session(db: AsyncSession, tenant, user) -> uuid.UUID:
    """Build org_unit→job→instance→stage→candidate→assignment→session chain."""
    from app.models import Session as SessionModel

    assignment, stage = await _make_assignment_with_stage(db, tenant, user)
    session = SessionModel(
        tenant_id=tenant.id,
        assignment_id=assignment.id,
        stage_id=stage.id,
        created_by=user.id,
    )
    db.add(session)
    await db.flush()
    return session.id


# ---------------------------------------------------------------------------
# The isolation test.
# ---------------------------------------------------------------------------
async def test_engine_dispatch_tokens_tenant_isolation(
    _apply_engine_token_rls: None,
    _create_tables: None,
) -> None:
    """Tenant A's dispatch token is NOT visible from tenant B's RLS context.

    Steps
    -----
    1. Seed tenant A + B rows + the FK graph for tenant A, using the bypass
       connection (postgres role, bypass_rls=true). Commit so the FK lookup
       in step 2 succeeds across connection boundaries.
    2. Insert a dispatch token under tenant A with ``app.current_tenant``
       set to tenant_a_id (still as postgres; policy USING check only blocks
       SELECT/UPDATE when nexus_app is the role — we verify the INSERT policy
       on commit).
    3. SELECT all rows under tenant B's context **as nexus_app** (``SET LOCAL
       ROLE nexus_app``) so ``rolbypassrls=false`` makes the policy evaluate.
       Assert 0 rows.
    4. Clean up committed rows (bypass connection).
    """
    # ---- Step 1: seed two tenants + FK graph --------------------------------
    # Use postgres/bypass so RLS doesn't block the insert chain.
    tenant_a_id: uuid.UUID
    tenant_b_id: uuid.UUID
    session_a_id: uuid.UUID

    async with _rls_engine.connect() as conn_bypass:
        # Explicit transaction + bypass flag so the seeding helpers work.
        await conn_bypass.execute(sqlalchemy.text("BEGIN"))
        await conn_bypass.execute(
            sqlalchemy.text("SET LOCAL app.bypass_rls = 'true'")
        )
        bypass_session = AsyncSession(bind=conn_bypass, expire_on_commit=False)

        tenant_a = await create_test_client(bypass_session)
        tenant_b = await create_test_client(bypass_session)
        await bypass_session.flush()

        user_a = await create_test_user(bypass_session, tenant_a.id)
        await bypass_session.flush()

        session_a_id = await _seed_session(bypass_session, tenant_a, user_a)
        await bypass_session.flush()

        await conn_bypass.execute(sqlalchemy.text("COMMIT"))

    tenant_a_id = tenant_a.id
    tenant_b_id = tenant_b.id

    # ---- Step 2: insert a dispatch token under tenant A --------------------
    # We insert as postgres with current_tenant set (policy WITH CHECK will
    # apply once the policy exists and the role is nexus_app, but here we're
    # still postgres so the insert succeeds unconditionally). The isolation
    # assertion in step 3 is what actually validates the policy.
    jti = uuid.uuid4()
    async with _rls_engine.connect() as conn_a:
        await conn_a.execute(sqlalchemy.text("BEGIN"))
        # Inline UUID — asyncpg does not support bound params in SET LOCAL.
        await conn_a.execute(
            sqlalchemy.text(f"SET LOCAL app.current_tenant = '{tenant_a_id}'")
        )
        await conn_a.execute(
            sqlalchemy.text(
                "INSERT INTO engine_dispatch_tokens"
                " (jti, tenant_id, session_id, expires_at)"
                " VALUES (:jti, :tenant_id, :session_id, :expires_at)"
            ),
            {
                "jti": str(jti),
                "tenant_id": str(tenant_a_id),
                "session_id": str(session_a_id),
                "expires_at": datetime.now(UTC) + timedelta(minutes=10),
            },
        )
        await conn_a.execute(sqlalchemy.text("COMMIT"))

    # ---- Step 3: query under tenant B with nexus_app role --------------------
    # nexus_app has rolbypassrls=false, so the tenant_isolation policy runs.
    # With app.current_tenant set to tenant_b_id, the USING predicate
    #   tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
    # resolves to tenant_b_id, which doesn't match the row's tenant_a_id.
    # Result: 0 rows.
    async with _rls_engine.connect() as conn_b:
        await conn_b.execute(sqlalchemy.text("BEGIN"))
        await conn_b.execute(sqlalchemy.text("SET LOCAL ROLE nexus_app"))
        # Inline UUID — bound params not allowed in SET LOCAL.
        await conn_b.execute(
            sqlalchemy.text(f"SET LOCAL app.current_tenant = '{tenant_b_id}'")
        )
        result = await conn_b.execute(
            sqlalchemy.text("SELECT jti FROM engine_dispatch_tokens")
        )
        rows = result.fetchall()
        await conn_b.execute(sqlalchemy.text("ROLLBACK"))

    # ---- Step 4: assert isolation -------------------------------------------
    assert rows == [], (
        f"Tenant B must not see tenant A's dispatch tokens, but got {rows!r}"
    )

    # ---- Cleanup: remove committed rows -------------------------------------
    # Bypass connection so the delete isn't blocked by RLS.
    async with _rls_engine.connect() as conn_clean:
        await conn_clean.execute(sqlalchemy.text("BEGIN"))
        await conn_clean.execute(
            sqlalchemy.text("SET LOCAL app.bypass_rls = 'true'")
        )
        await conn_clean.execute(
            sqlalchemy.text(
                "DELETE FROM engine_dispatch_tokens WHERE jti = :jti"
            ),
            {"jti": str(jti)},
        )
        # ON DELETE CASCADE on sessions/assignments/candidates means
        # deleting the clients will cascade through the FK chain.
        await conn_clean.execute(
            sqlalchemy.text(
                "DELETE FROM clients WHERE id = :a OR id = :b"
            ),
            {"a": str(tenant_a_id), "b": str(tenant_b_id)},
        )
        await conn_clean.execute(sqlalchemy.text("COMMIT"))


# ---------------------------------------------------------------------------
# Negative-control test.
# ---------------------------------------------------------------------------
async def test_negative_control_broken_policy_leaks_rows(
    _apply_engine_token_rls: None,
    _create_tables: None,
) -> None:
    """Negative control: a permissive tenant_isolation policy leaks cross-tenant rows.

    This test deliberately breaks the ``tenant_isolation`` policy by replacing
    it with ``USING (true) WITH CHECK (true)``, then re-runs the same query
    that the isolation test uses. The expected outcome is that tenant B CAN
    see tenant A's row — confirming that the positive test would catch this
    regression if it were committed. The correct policy is restored before
    this test returns.

    Sequence
    --------
    1. Break policy → USING (true).
    2. Seed tenant A + dispatch token.
    3. SELECT under tenant B as nexus_app → assert rows NOT empty (leak confirmed).
    4. Restore correct policy.
    5. SELECT under tenant B again → assert rows empty (policy works again).
    6. Clean up.
    """
    # ---- Break the policy ---------------------------------------------------
    # After this point the schema is in a degraded state — every subsequent
    # line MUST be inside try/finally so the restore runs no matter what.
    async with _rls_engine.begin() as conn_ddl:
        await conn_ddl.execute(sqlalchemy.text(_DROP_TENANT_POLICY))
        await conn_ddl.execute(sqlalchemy.text(_CREATE_PERMISSIVE_POLICY))

    try:
        # ---- Seed data ------------------------------------------------------
        async with _rls_engine.connect() as conn_bypass:
            await conn_bypass.execute(sqlalchemy.text("BEGIN"))
            await conn_bypass.execute(
                sqlalchemy.text("SET LOCAL app.bypass_rls = 'true'")
            )
            bypass_session = AsyncSession(bind=conn_bypass, expire_on_commit=False)

            tenant_a = await create_test_client(bypass_session)
            tenant_b = await create_test_client(bypass_session)
            await bypass_session.flush()
            user_a = await create_test_user(bypass_session, tenant_a.id)
            await bypass_session.flush()
            session_a_id = await _seed_session(bypass_session, tenant_a, user_a)
            await bypass_session.flush()
            await conn_bypass.execute(sqlalchemy.text("COMMIT"))

        tenant_a_id = tenant_a.id
        tenant_b_id = tenant_b.id

        jti = uuid.uuid4()
        async with _rls_engine.connect() as conn_a:
            await conn_a.execute(sqlalchemy.text("BEGIN"))
            await conn_a.execute(
                sqlalchemy.text(f"SET LOCAL app.current_tenant = '{tenant_a_id}'")
            )
            await conn_a.execute(
                sqlalchemy.text(
                    "INSERT INTO engine_dispatch_tokens"
                    " (jti, tenant_id, session_id, expires_at)"
                    " VALUES (:jti, :tenant_id, :session_id, :expires_at)"
                ),
                {
                    "jti": str(jti),
                    "tenant_id": str(tenant_a_id),
                    "session_id": str(session_a_id),
                    "expires_at": datetime.now(UTC) + timedelta(minutes=10),
                },
            )
            await conn_a.execute(sqlalchemy.text("COMMIT"))

        # ---- SELECT under tenant B with broken policy → expect leak ---------
        async with _rls_engine.connect() as conn_b:
            await conn_b.execute(sqlalchemy.text("BEGIN"))
            await conn_b.execute(sqlalchemy.text("SET LOCAL ROLE nexus_app"))
            await conn_b.execute(
                sqlalchemy.text(f"SET LOCAL app.current_tenant = '{tenant_b_id}'")
            )
            result = await conn_b.execute(
                sqlalchemy.text("SELECT jti FROM engine_dispatch_tokens")
            )
            rows_broken = result.fetchall()
            await conn_b.execute(sqlalchemy.text("ROLLBACK"))

        # Broken policy MUST leak rows — this proves the positive test is meaningful.
        assert rows_broken != [], (
            "With a permissive policy, tenant B should see tenant A's rows "
            f"(negative-control failure: got {rows_broken!r})"
        )

    finally:
        # ---- Restore the correct policy — always runs -----------------------
        async with _rls_engine.begin() as conn_ddl:
            await conn_ddl.execute(sqlalchemy.text(_DROP_TENANT_POLICY))
            await conn_ddl.execute(sqlalchemy.text(_CREATE_TENANT_POLICY))

    # ---- Verify isolation is restored ---------------------------------------
    # After the finally block so a restore failure surfaces as a separate
    # exception rather than being swallowed by the original assertion error.
    async with _rls_engine.connect() as conn_b2:
        await conn_b2.execute(sqlalchemy.text("BEGIN"))
        await conn_b2.execute(sqlalchemy.text("SET LOCAL ROLE nexus_app"))
        await conn_b2.execute(
            sqlalchemy.text(f"SET LOCAL app.current_tenant = '{tenant_b_id}'")
        )
        result2 = await conn_b2.execute(
            sqlalchemy.text("SELECT jti FROM engine_dispatch_tokens")
        )
        rows_restored = result2.fetchall()
        await conn_b2.execute(sqlalchemy.text("ROLLBACK"))

    assert rows_restored == [], (
        f"After restoring policy, tenant B must see 0 rows, got {rows_restored!r}"
    )

    # ---- Cleanup ------------------------------------------------------------
    async with _rls_engine.connect() as conn_clean:
        await conn_clean.execute(sqlalchemy.text("BEGIN"))
        await conn_clean.execute(
            sqlalchemy.text("SET LOCAL app.bypass_rls = 'true'")
        )
        await conn_clean.execute(
            sqlalchemy.text(
                "DELETE FROM engine_dispatch_tokens WHERE jti = :jti"
            ),
            {"jti": str(jti)},
        )
        await conn_clean.execute(
            sqlalchemy.text(
                "DELETE FROM clients WHERE id = :a OR id = :b"
            ),
            {"a": str(tenant_a_id), "b": str(tenant_b_id)},
        )
        await conn_clean.execute(sqlalchemy.text("COMMIT"))
